# Generated by Django 5.0 on 2024-12-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('monthly_price_cents', models.IntegerField()),
                ('monthly_price_yearly_subscription_in_cents', models.IntegerField()),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_home', models.CharField(db_index=True, max_length=255)),
                ('team_away', models.CharField(db_index=True, max_length=255)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('tournament_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'games',
                'indexes': [models.Index(fields=['team_home', 'team_away'], name='games_team_ho_2e5dcc_idx'), models.Index(fields=['tournament_name'], name='games_tournam_541592_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreamingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=False)),
                ('highlights', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.game')),
                ('streaming_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.streamingpackage')),
            ],
            options={
                'db_table': 'offers',
                'indexes': [models.Index(fields=['game', 'streaming_package'], name='offers_game_id_f15032_idx'), models.Index(fields=['live', 'highlights'], name='offers_live_0bd71c_idx')],
                'unique_together': {('game', 'streaming_package')},
            },
        ),
    ]
