# Generated by Django 5.0.4 on 2024-12-29 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_home', models.CharField(max_length=255)),
                ('team_away', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('tournament_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='StreamingPackage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('monthly_price_cents', models.IntegerField(null=True)),
                ('monthly_price_yearly_subscription_in_cents', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='StreamingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=False)),
                ('highlights', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('streaming_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.streamingpackage')),
            ],
            options={
                'db_table': 'offers',
            },
        ),
    ]
