# Generated by Django 4.2 on 2024-11-16 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_home', models.CharField(max_length=255)),
                ('team_away', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('tournament_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('monthly_price_cents', models.IntegerField(blank=True, null=True)),
                ('monthly_price_yearly_subscription_in_cents', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=False)),
                ('highlights', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_offers', to='streaming.game')),
                ('streaming_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='streaming.streamingpackage')),
            ],
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['team_home'], name='streaming_g_team_ho_48576f_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['team_away'], name='streaming_g_team_aw_b22289_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['starts_at'], name='streaming_g_starts__39441e_idx'),
        ),
        migrations.AddIndex(
            model_name='streamingoffer',
            index=models.Index(fields=['game', 'streaming_package'], name='streaming_s_game_id_6c0d5e_idx'),
        ),
    ]
