version: '3.8'

services:
  frontend:
    container_name: streaming-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001  # Updated to match new backend port
    depends_on:
      - backend

  backend:
    container_name: streaming-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Changed from 5000:5000 to 5001:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/streaming_db
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=streaming_db
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: streaming-db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=streaming_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: